# Generated by Django 3.2 on 2021-07-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='county',
            new_name='country',
        ),
    ]
