# Generated by Django 3.2 on 2021-07-30 14:46

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_review_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='/placeholder.png', force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to=''),
        ),
    ]
